### ISSUE TITLE
STA9750 aaronkcooper MiniProject #00

### ISSUE THREAD

**Issue by aaronkcooper** [aaronkcooper/STA9750-2024-FALL#1]
Hi @michaelweylandt!

I've created my STA9750 website - check it out!

https://aaronkcooper.github.io/STA9750-2024-FALL

**Comment by michaelweylandt** [comment]
Thanks @aaronkcooper !

Peer Feedback:

- @laurencardieri
- @Malexandra-Jerez
- @CristelKZuniga

Please a look at the website associated with this GitHub repo
and provide some peer feedback to @aaronkcooper.

Website URL should be: https://aaronkcooper.github.io/STA9750-2024-FALL/

If that link doesn't work, please check out the GitHub profile for @aaronkcooper and
see if you can help them get it working.

At a minimum, please note:

1. Something you like about the submission.
2. A suggestion on how to improve it.

Feel free to link to other repos, the course documentation, or other useful
examples.

This submission is ungraded, so there's you don't need to provide
a numerical score.

Thanks!
@michaelweylandt

CC: @charles-ramirez

**Comment by Malexandra-Jerez** [comment]
Hi Aaron !

Great Web! Here is my obs.

   1. Something you like about the submission. - Text, it looks like you
   know how to add text well. Name is nice and big. Curious about your
   pursuit of an MS...is it for career advancement or just b/c you love it?
   2. A suggestion on how to improve it. - Image, I'm a visual person and
   maybe an image would have made it fun.

Have a great day!
Kindly,
Maria Alexandra Jerez

**Comment by CristelKZuniga** [comment]
Hi @aaronkcooper, I was successfully able to open your website! I liked that you made an strong introduction with just few words. I'd only  suggest to add some hyperlinks to your contact information, such as email or LikendIn account.

**Comment by laurencardieri** [comment]
Hi @aaronkcooper! I really like the font/color scheme you choice and how your presented your information in a concise manner. A suggestion to improve would be to include either pictures or links to make the page more interactive.
